# Generated by Django 6.0.4 on 2026-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('material_type', models.CharField(choices=[('yearbook', 'Yearbook'), ('newspaper', 'Newspaper'), ('photo', 'Photo'), ('program', 'Program'), ('athletic_record', 'Athletic Record'), ('fine_arts', 'Fine Arts Material'), ('general_document', 'General Document'), ('other', 'Other')], default='other', max_length=100)),
                ('material_year', models.PositiveIntegerField(blank=True, help_text='Approximate year of the material, if known.', null=True)),
                ('title_or_description', models.CharField(help_text='Short title or description of the material.', max_length=255)),
                ('details', models.TextField(help_text='Additional context, condition, names, dates, or historical relevance.')),
                ('permission_acknowledged', models.BooleanField(default=False, help_text='Visitor confirms they understand the association must review materials before public display.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('followed_up', 'Followed Up'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('archived', 'Archived')], default='new', max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contribution Inquiry',
                'verbose_name_plural': 'Contribution Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
