# Generated by Django 6.0.4 on 2026-04-25 18:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('legacy', 'Legacy Alumni'), ('athletics', 'Athletics'), ('fine_arts', 'Fine Arts'), ('community', 'Community Impact'), ('faculty_staff', 'Faculty and Staff')], default='legacy', max_length=100)),
                ('short_summary', models.TextField(help_text='Short summary used for cards and kiosk display.')),
                ('biography', wagtail.fields.RichTextField(blank=True)),
                ('major_achievements', wagtail.fields.RichTextField(blank=True)),
                ('legacy_statement', wagtail.fields.RichTextField(blank=True, help_text='Explain why this person matters to the GFHS legacy.')),
                ('featured_on_homepage', models.BooleanField(default=False)),
                ('featured_on_kiosk', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AlumniIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
