# Generated by Django 6.0.4 on 2026-04-26 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnidetailpage',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Primary photo used on alumni cards, detail pages, homepage features, and kiosk displays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
