# Generated by Django 6.0.4 on 2026-04-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleventpage',
            name='primary_image',
            field=models.ForeignKey(blank=True, help_text='Primary image used on history cards, public detail pages, and kiosk displays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
