# Generated by Django 6.0.4 on 2026-04-26 07:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_historicaleventpage_primary_image'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItemPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('archive_year', models.PositiveIntegerField(blank=True, help_text='Year connected to this archive item, if known.', null=True)),
                ('document_type', models.CharField(choices=[('yearbook', 'Yearbook'), ('newspaper', 'Newspaper'), ('photo', 'Photo'), ('program', 'Program'), ('athletic_record', 'Athletic Record'), ('fine_arts', 'Fine Arts'), ('general_document', 'General Document')], default='general_document', max_length=100)),
                ('short_description', models.TextField(help_text='Short description shown on archive cards.')),
                ('full_description', wagtail.fields.RichTextField(blank=True, help_text='Longer explanation, context, or historical notes about this item.')),
                ('featured_on_kiosk', models.BooleanField(default=False)),
                ('archive_file', models.ForeignKey(blank=True, help_text='Upload the related PDF, scan, program, newspaper, yearbook, or document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('primary_image', models.ForeignKey(blank=True, help_text='Optional thumbnail or preview image for this archive item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
