# Generated by Django 6.0.4 on 2026-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_archiveitempage'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitempage',
            name='credit_line',
            field=models.CharField(blank=True, help_text='Public credit line, if one should be displayed.', max_length=255),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='digitization_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('digitized', 'Digitized'), ('quality_checked', 'Quality Checked'), ('published', 'Published')], default='not_started', help_text='Tracks where this item is in the preservation workflow.', max_length=100),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private admin notes. These are not intended for public display.'),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='permission_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('approved', 'Approved for Public Display'), ('internal_only', 'Internal Use Only'), ('needs_review', 'Needs Review'), ('restricted', 'Restricted')], default='needs_review', help_text='Controls whether the item has been reviewed for public display.', max_length=100),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='physical_location',
            field=models.CharField(blank=True, help_text='Physical storage location, box number, binder, shelf, cabinet, or future NAS/archive reference.', max_length=255),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='public_display_approved',
            field=models.BooleanField(default=False, help_text='Check only after the item has been reviewed and approved for public display.'),
        ),
        migrations.AddField(
            model_name='archiveitempage',
            name='source_or_donor',
            field=models.CharField(blank=True, help_text='Person, family, department, organization, or source that provided the item.', max_length=255),
        ),
    ]
