# Generated by Django 6.0.4 on 2026-04-25 18:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(default='A living digital monument honoring the history, achievements, and people who shaped Great Falls High School.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Preserving the Legacy of Great Falls High School', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(blank=True, default='The Great Falls High School Legacy Alumni Association exists to preserve history, honor distinguished alumni, and celebrate the culture and achievements of a historic school community.'),
        ),
    ]
